language: go
go:
  - 1.6.3
  - 1.7
sudo: false
install:
  - go get -d -t -v ./...
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
