language: go
go:
  - 1.6.3
  - 1.7
sudo: false
install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - go install -v . ./cmd/...
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/bradfitz/goimports
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/davecgh/go-spew/spew
script:
  - export PATH=$PATH:$HOME/gopath/bin
