language: go
go:
  - 1.5.3
  - 1.6
sudo: false
before_install:
  - gotools=golang.org/x/tools
install:
  - go get -d -t -v ./...
  - go get -v $gotools/cmd/cover
  - go get -v github.com/bradfitz/goimports
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
