language: go
go:
  - release
  - tip
install:
  - go get -d -t -v ./...
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/GeertJohan/fgt
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go vet
  - fgt golint .
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=profile.cov -service=travis-ci
