language: go
go: release
install:
- go get code.google.com/p/go.tools/cmd/vet
- go get github.com/GeertJohan/fgt
- go get github.com/golang/lint/golint
- go get -d -t -v ./...
script:
- export PATH=$PATH:$HOME/gopath/bin
- fgt golint -min_confidence=0.9 *.go
- go vet *.go
- go test -v ./...
