blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/btcsuite/btcd/discussions
    about: For general or troubleshooting questions or if you're not sure what issue type to pick.
  - name: Community Slack
    url: https://lightning.engineering/slack.html
    about: Please ask and answer questions here.
  - name: Security issue disclosure policy
    url: https://github.com/lightningnetwork/lnd#security
    about: Please refer to this document when reporting security related issues.
